.github/workflows/lint.yml, .github/workflows/tests.yml, .mergify.yml
We're using `master` instead of `main` as the default branch, so CI config files need to be changed to use the former.
=> ci: main -> master

.github/CODEOWNERS
Change `solidity/` to `ethereum/solidity/`
=> fix: Fix codeowners Solidity dir.

.github/workflows/lint.yml, .github/workflows/tests.yml, ethereum/solidity/wrappers/QuantumGravityBridge.sol/wrapper.go
=> chore: Regenerate contract ABI bindings.

.github/workflows/tests.yml
Fixes https://github.com/celestiaorg/quantum-gravity-bridge/issues/59
Verified on https://github.com/rootulp/quantum-gravity-bridge/runs/5505826872?check_suite_focus=true
Inspired by https://github.com/FrankieIsLost/forge-template/blob/master/.github/workflows/CI.yml#L19-L28
=> feat(ci): run forge test

README.md
- Instructions for submodules
- Clean up ToC
=> chore: Improve readme.

ethereum/solidity/src/QuantumGravityBridge.sol
=> chore: Add period at end of comment.

ethereum/solidity/src/lib/tree/namespace/NamespaceMerkleTree.sol, ethereum/solidity/src/lib/tree/namespace/test/NamespaceMerkleTree.t.sol
=> feat: Refactor and add inner node verification logic.

scripts/Dockerfile_Environment
Documents the usage of the environment Dockerfile
=> docs: document the use of environment Dockerfile

.github/workflows/lint.yml, .github/workflows/tests.yml, Makefile
Closes https://github.com/celestiaorg/quantum-gravity-bridge/issues/158
=> ci: add solidity formatting check and tweak go wrappers CI check

src/lib/verifier/DAVerifier.sol, src/lib/verifier/test/DAVerifier.t.sol
Closes https://github.com/celestiaorg/quantum-gravity-bridge/issues/161
I will open a subsequent PR to provide ways to authenticate the proofs.
=> feat: support compute square size from proofs

.github/workflows/labels.yml
Closes https://github.com/celestiaorg/quantum-gravity-bridge/issues/108
=> ci: add labels workflow

scripts/Dockerfile_Environment
This is using the same environment as the CI for wrapper generation. Previously, it was using latest ethereum dev tools and a different go version w which was resulting in a different wrapper
=> chore: use the same environment as CI

.github/dependabot.yml
=> ci: add auto reviewers to dependabot PRs

.github/CODEOWNERS
=> chore: update the CODEOWNERS

.github/workflows/lint.yml, .markdownlint.yaml, README.md
Closes https://github.com/celestiaorg/quantum-gravity-bridge/issues/185
=> ci: add support for markdown lint

.github/dependabot.yml
depends on https://github.com/celestiaorg/quantum-gravity-bridge/pull/199
=> ci: dependabot check go dependencies

src/lib/verifier/DAVerifier.sol
closes https://github.com/celestiaorg/quantum-gravity-bridge/issues/193
The test that fails if this fix is absent is in here: https://github.com/celestiaorg/quantum-gravity-bridge/pull/160
=> fix: fix da verifier row root node creation

.github/workflows/labels.yml
=> ci: add dependencies to the list of required labels

src/lib/verifier/DAVerifier.sol
Closes https://github.com/celestiaorg/blobstream-contracts/issues/237
=> chore: make the DAVerifier methods internal

go.mod
We need to bump to v4 because we have breaking changes that we want to release.
=> chore: bump to v4
